services:
  ps01-support-agent:
    build: .
    container_name: ps01-support-agent
    env_file:
      - .env
    stdin_open: true
    ports:
      - "5000"
    tty: true
    networks:
      - agents-net

networks:
  agents-net:
    external: true
